- name: Create Prometheus directory
  file:
    path: /opt/prometheus
    state: directory

- name: Download Prometheus
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz
    dest: /opt/prometheus
    remote_src: yes

